### PR TITLE
Add choo-cli

### PR DESCRIPTION
**Pull request by MattMcFarland**
Since choo-cli is a viable alternative and works very well, please consider adding this to the readme.  A lot of work went into it from the choo community.

### CODE REVIEW

**Review by YerkoPalma — APPROVED** [review]

**Comment by MattMcFarland** [comment]
Seems travis CI is messed up - failing build but not because of my changes (something to do with package.json ???)

**Comment by yoshuawuyts** [comment]
Could you perhaps add this to a `## See Also` section instead. The initial paragraph is a bit cluttered if we add three suggestions. Thanks!

**Comment by YerkoPalma** [comment]
I think a see also sections is a good idea. Maybe point to the [templates section](https://github.com/choojs/awesome-choo#cli-templates) of the awesome choo list (also add this repo there)

**Comment by MattMcFarland** [comment]
Proposed changes are in pr #3

**Pull request closed without merging**
